<pre id=logo1 style="text-align: center;margin-top: 10vh;font-size: 0.35vw;color: lime;">
                                   `.-:+oooyyyyyy. +ssyyysoo::-.                                                                                                                                                                                                                                            
                              `-:oyyyyyyyyyyyyyyy. oysyyyyyyyyyyyyo:-`                                                                                                                                                                                                                                      
                         `.:osyyyyyyyyyyyyyyyyyyy. oyysyyyyyyyyyyyyyyyso:.`                                                                                                                                                                                                                                 
                       -/syyyyyyyyyyyyyyyyyyyyyyy. oyyyysyyyyyyyyyyyyyyyyys/-                                                                                                                                                                                                                               
                    -+syyyyyyyyyyyyyyyyyyyyyyyyyy. oyyyyyyyyyyyyyyyyyyyyyyyyys+-                                                                                                                                                                                                                            
                 ./syyyyyyyyyyyyyyyyyyyyyyyyyyyyy. oyyyyyysyyyyyyyyyyyyyyyyyyyyys/.                                                                                                                                                                                                                         
               `:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy. oyyyyyyyoyyyyyyyyyyyyyyyyyyyyyyy+.                                                                                                                                                                                                                       
             ``.+yoyoyoysyyyyyyyyyyyyyyyyyyyyyyyy. oyyyyyyyyssyyyyyyyyyyyyyyyyyyyyys:                                                                                                                                                                                                                       
           ./ss:`-oyyyyysyoyossysyyyyyyyyyyyyyyyy. oyyyyyyyyyysyyyyyyyyyyyyyyyyyys/`.+//.                                                                                                                                                                                                                   
          :syyyys:`-oyyyyyyyyyyyyyssssssssyyyyyyy. oyyyyyyyyyysyyyyyyyyyyyyyyyys/`.+yosys-                                                                                                                                                                                                                  
        `+yyyyyyyys:`-oyyyyyyyyyyyyyyyyyyysssssos. +syyyyyyyyyyysyyyyyyyyyyyys/`.+yyy+yyyy/`                                                                                                                                                                                                                
       -syyyyyyyyyyyo:`-oyyyyyyyyyyyyyyyoo//... `  ``...:/+osyyyyoyyyyyyyyys/..+yyyyssyyyyys-                                                                                                                                                                                                               
      -yyyyyyyyyyyyyyyo-`-oyyyyyyyyyso/:.`                ``-/ooyyssyyyyys/../syyyyyoyyyyyyyy-                                                                                                                                                                                                              
     /yyyyyyyyyyyyyyyyyyo-`:oyyyyo/ossoo+o+:-`         `-/o++oosyo+osyys+../syyyyyyy+yyyyyyyyy:                                                                                                                                                                                                             
    /yyyyyyyyyyyyyyyyyyyyyo-`:o+.-ss-`   .-/o+/.`   `-+s+/-`   ./y/..++../syyyyyyyyoyyyyyyyyyyy:                `---------.            .------------.`         .---------------       -------------`           ----------------.      `-------` .-------.       -------------`           `--------------`   
   :yyyyyyyyyyyyyyyyyyyyyyyy/`   +y-        `-+oo-./ss/.         oy.   -syyyyyyyyyyoyyyyyyyyyyys-               /yyyyyyyyyy`           +yyyyyyyyyyyyyso-       /yyyyyyyyyyyyyys       yyyyyyyyyyyyyso/`        oyyyyyyyyyyyyyyy/      .yyyyyyy: :yyyyyyyo      `yyyyyyyyyyyyyso/`        :yyyyyyyyyyyyyy:   
  `syyyyyyyyyyyyyyyyyyyyyys/`   `ss            `+yss-`           -y:   `+yyyyyyyyyosyyyyyyyyyyyys`              oyyyyyyyyyy-           +yyyyyyyyyyyyyyyy:      /yyyyyyyysssssso       yyyyyyyysyyyyyyys`       osssyyyyyyyyysss/      .yyyyyyy: :yyyyyyyo      `yyyyyyyysyyyyyyyo`       :yyyyyyysssssss-   
  oyyyyyyyyyyyyyyyyyyyyssy+     `ss           `/ss/so.           -y/     .oyyyyyyyoyyyyyyyyyyyyyy+             .yyyyyyyyyyy+           +yyyyyyy-+yyyyyyyo      /yyyyyyyo```````       yyyyyyyo`/yyyyyyy:       ````oyyyyyyy/````      .yyyyyyy: :yyyyyyyo      `yyyyyyy+.+yyyyyyy-       :yyyyyyy-``````    
 -yyyyyyyyyyyyyyyysssssyy:       +s          .os/` .os:`         -y.      `oyyyyyssyyyyyyyyyyyyyyy-            /yyyyyyyyyyyy`          +yyyyyyy` syyyyyyo      /yyyyyyy+              yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ -yyyyyyy-       :yyyyyyy.          
 syyyyyyyyyyyyyysssyyyyy:        /y-      ``:ys-`````/yo.`       +y`       `oyyyy+yyyyyyyyyyyyyyyyo            oyyyyyyyyyyyy-          +yyyyyyy` syyyyyyo      /yyyyyyy+              yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ -yyyyyyy-       :yyyyyyy.          
-yyyyyyyyyyyyossyyyyyyy/         .ys///ooosyyss+++++++ssysooo+//:y+`        .yyyy+yyyyyyyyyyyyyyyyy-          .yyyyyyyyyyyyy+          +yyyyyyy` syyyyyyo      /yyyyyyy+              yyyyyyyo .yyyyyyy-           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ :yyyyyyy-       :yyyyyyy.          
+yyyyyyyyssyyyyyyyyyyys     `-/+ossy+:...-ss.           /y+...-:yyoso//.`    :yyoyyyyyyyyyyyyyyyyyy/          /yyyyyy/yyyyyys`         +yyyyyyy` syyyyyyo      /yyyyyyys/////:        yyyyyyys/yyyyyys:            oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyyo+yyyyyys:        :yyyyyyy+//////    
yyyyyyssyyyyyyyyyyyyyy:  ./os+/-` `ss`  :yo.             -ys`  :y/  .:/os+-`  yyoyyyyyyyyyyyyyyyyyyy          oyyyyyy:yyyyyyy.         +yyyyyyy`:yyyyyyyo      /yyyyyyyyyyyyys        yyyyyyyyyyyyyy/`             oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyyyyyyyyy/`         :yyyyyyyyyyyyys    
yysyssyyyyyyyyyyyyyyyy`-oyo-`      -y+ :y/      `..`      .ss`.yo`      ./sy/`/ssyyyyyyyyyyyyyyyyyyy         .yyyyyyy-oyyyyyy+         +yyyyyyyyyyyyyyyy/      /yyyyyyyyooooo+        yyyyyyyysyyyyyyo:            oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyyssyyyyyys-        :yyyyyyysoooooo    
ssyyyyyyyyyyyyyyyyyyys:ys-          /yoy/      +yyyys-     .ssys`         `/yo/+yyyyyyyyyyyyyyyyyyyy         :yyyyyyy`+yyyyyys`        +yyyyyyyyyyyyyyyo`      /yyyyyyy+              yyyyyyyo :yyyyyyy.           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ /yyyyyyy.       :yyyyyyy.          
``````````````````````yy`            oyo      -yyyyyys      .yy-            +y:`````````````````````         oyyyyyyyyyyyyyyyy.        +yyyyyyy+++++/-.        /yyyyyyy+              yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ -yyyyyyy-       :yyyyyyy.          
sssssssssssssssssssss:+y+`          :yyy:     `+yyyys:      oyys`          -ys+ssssssssssssssssssooo        .yyyyyyyyyyyyyyyyy+        +yyyyyyy`               /yyyyyyy+              yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ -yyyyyyy-       :yyyyyyy.          
yyyyyyyyyyyyyyyyyyyyy/ :ys/`       .yo`+y/      `::-`     .oy.-y+        .oyo`/yyyyyyyyyyyyyyyysssyy        :yyyyyyy+::syyyyyys`       +yyyyyyy`               /yyyyyyy+              yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ -yyyyyyy-       :yyyyyyy.          
yyyyyyyyyyyyyyyyyyyy+y: `-+s+/-`  `oy.  +y/              .ss-  /y-   .:/so/.  syyyyyyyyyyyyyosyyyyyy        oyyyyyys   /yyyyyyy.       +yyyyyyy`               /yyyyyyy+              yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyy: :yyyyyyyo      `yyyyyyy/ -yyyyyyy-       :yyyyyyy.          
/yyyyyyyyyyyyyyyyyyyoyo    `./+os+oy/.`  :yo`           :yo.  ..ss+oso/-`    :yyyyyyyyyyssysyyyyyyy/       `syyyyyyo   -yyyyyyy/       +yyyyyyy`               /yyyyyyys:::::::       yyyyyyyo .yyyyyyy:           oyyyyyyy:          .yyyyyyys:oyyyyyyy-      `yyyyyyy/ -yyyyyyy:       :yyyyyyy/::::::.   
-yyyyyyyyyyyyyyyyyyoyyy/        `-ys/+oososys+++/:::++++yy+sooo/+yo``       .yyyyyyyyssyyyyyyyyyyyy`       -yyyyyyy:    yyyyyyyo       +yyyyyyy`               /yyyyyyyyyyyyyys       yyyyyyyo .yyyyyyy+           oyyyyyyy:          `oyyyyyyyyyyyyyyy+`      `yyyyyyy/ -yyyyyyyo       :yyyyyyyyyyyyyy:   
 syyyyyyyyyyyyyyyyy+yyyy-        :y:    ```.+ys/:::::+ys-````    ss`       `oyyyyssssyyyyyyyyyyyyyo        oyyyyyyy-    oyyyyyyy.      +yyyyyyy`               /yyyyyyyyyyyyyys       yyyyyyyo  +yyyyyyy.          oyyyyyyy:            -+oyyyyyyyyyo+-        `yyyyyyy/  oyyyyyyy-      :yyyyyyyyyyyyyy:   
 -yyyyyyyyyyyyyyyy+syyyyy:       +s`         :ss-  `/s+`         :y.      `+yyyssyyyyyyyyyyyyyyyyy-        `......`     `.......       `.......                `..............`       `......`  `.......`          `.......`               `...:...`            .......`  `.......`      `..............`   
  oyyyyyyyyyyyyyyyoyyyyyyy/     `ss           `/yo/so-           -y-     .oyosyyyyyyyyyyyyyyyyyyy+                                                                                                                                                                                                          
  `syyyyyyyyyyyyyssyyyyyyyy+.   `ys            `oyys-            -y:    .oyyyyyyyyyyyyyyyyyyyyyys`         .::::-`     .::::.    -:::   -::::::   `::::`-::.    .::::-    `::::::.           `:::`   ::::`.::-   -:::-`:::    `-::::.    :::: .:::     `::::`     :::::::-   `-::::.    .:::::-`     .::::- 
   :yyyyyyyyyyyyyoyyyyyyyyyys`   +s.         .:so--os+-`         /y.   :syyyyyyyyyyyyyyyyyyyyyys-         .syyyyy+    oyysyys.   oyyo   /yyyooo`  -yyyy/+yy:   -yyysyy/   .yyysoo-           .yyy-  `yyyy/:yy+   oyyys.yyy    oyyyyyy-   +yys oyyo     /yyyy/     ooyyyso/   /yyysyy/   :yyysyys`   .syyyyyo
    /yyyyyyyyyyyssyyyyyyyys/../:`-ys.    `.-+s+-`   `/os+-.    `/y+`:+:`-oyyyyyyyyyyyyyyyyyyyyy:          oyyssyys    yyy/yyy+   oyyo   /yyy      -yyyysoyy:   /yyy/yy+   .yyy:              .yyy-  `yyyys/yy+   oyyyy/yyy   :yyy+syy+   /yys`yyy/     oyyyyo       yyy+     oyys+yys   :yyy/yyy.   +yyyoyyy
     /yyyyyyyyyy+yyyyyyys/..+syy+:oyyo//ooo+-`        `-/oooo/+ssoosyyyo:`-oyyyyyyyyyyyyyyyyyy/           /yyyys+/    yyy/+++:   oyyo   /yyy...   -yyyyyyyy:   /yyy-++:   .yyy:.`            .yyy-  `yyyyysyy+   oyyyyyyyy   :yyy+syyo   .yyy:yyy:    .syyyys.      yyy/     oyyo+yys   :yyy/yyy.   -yyyys++
      -yyyyyyyysoyyyyys+../syyyyyysyyoo-..`               `.-/osyyyyyyyyyo-`-oyyyyyyyyyyyyyyy-            `:syys-     yyy/       oyyo   /yyysss`  -yyyyyyyy:   /yyy`      .yyyyso            .yyy-  `yyyyyyyy+   oyyyyyyyy   :yyy+syyo   `yyysyyy`    -yyyyyy-      yyy/     oyyo+yys   :yyyyyy/`    :syyy:`
       -syyyyyyoyyyyy+../syyyyyyyysoyyyso+/:..```  `  `..//ooyyyyyyyyyyyyyyo-`:oyyyyyyyyyyys-             :/+yyyy+    yyy/://-   oyyo   /yyy...   -yyyyyyyy:   /yyy-//-   .yyy/..            .yyy-  `yyyyyyyy+   oyysyyyyy   :yyy+syyo    oyyyyyy     oyyssyy+      yyy/     oyyo+yys   :yyy+yyy.   -/+yyyyo
        `+yyyyyoyyy+.`/syyyyyyyyyyyysyyyyyyyyysss. +ooosssyyyyyyyyyyyyyyyyyyyo-`:syyyyyyyy/`              syyooyyy-   yyy/yyy+   oyyo   /yyy      -yyyoyyyy:   /yyy:yy+   .yyy-              .yyy-  `yyy/yyyy+   oyy:syyyy   :yyy+syyo    +yyyyy/    `syyssyys      yyy/     oyyo+yys   :yyy:yyy.   +yys+yyy
          -syyoyy+.`/syyyyyyyyyyyyyyyosyyyyyyyyyy. oyyyyyyssssssssyyyyyyyyyyyyyo-`:syyyys-                oyyssyyy.   yyy+yyy/   oyyo   /yyy...   -yyy:syyy:   /yyy+yy+   .yyy:..`           .yyy-  `yyy`yyyy+   oyy-/yyyy   .yyyosyy+    -yyyyy:    -yyy--yyy-     yyy/     oyyssyys   :yyy:yyy/   +yyyoyyy
           ./oo+.`/syyyyyyyyyyyyyyyyyysyyyyyyyyyy. oyyyyyyyyyyyyyyysysyoyoysyyyyyo-`:ss/.                 .osyyys:    /sysyso`   oyyo   /yyysss`  -yyy./yyy-   .syyyyo-   .yyysss:           .yyy-  `yyy /yyy/   oyy-`syys    +syyyso`    `yyyyy`    :yyy..yyy:     yyy/     :syyyss-   :yyy.syy+   `osyyys+
             ```/syyyyyyyyyyyyyyyyyyyyyssyyyyyyyy. oyyyyyyyyyyyyyyyyyyyyyyysyoyoyoy+.``                     ....`       ...`     ....   `......    ...  ...`     ....      ......`            ...`   ... `...`   ...` `...     `...`       .....     ....  ....     ...`      `....     `... ...`     `...` 
               `+yyyyyyyyyyyyyyyyyyyyyyyyoyyyyyyy. oyyyyyyyyyyyyyyyyyyyyyyyyyyyyysy:`                                                                                                                                                                                                                       
                 ./syyyyyyyyyyyyyyyyyyyyyyssyyyyy. oyyyyyyyyyyyyyyyyyyyyyyyyyyyys:.                                                                                                                                                                                                                         
                    -+syyyyyyyyyyyyyyyyyyyyssyyyy. oyyyyyyyyyyyyyyyyyyyyyyyyys+-                                                                                                                                                                                                                            
                       -/syyyyyyyyyyyyyyyyyyssyyy. oyyyyyyyyyyyyyyyyyyyyyys/-                                                                                                                                                                                                                               
                          .:osyyyyyyyyyyyyyyyysyy. oyyyyyyyyyyyyyyyyyyso:.                                                                                                                                                                                                                                  
                              .-:oyyyyyyyyyyyyyos. oyyyyyyyyyyyyyyo:-`                                                                                                                                                                                                                                      
                                    .-:+oooyyyyyo. oyyyyyooo::-.                                                                                                                                                                                                                                            

        </pre>
        