<pre style="text-align: center;margin-left: 4vh;margin-top: 10vh;font-size: 0.11vw;color: lime;">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        :/:                                           :+/`                                                    `/+:                                                     -+/.                                                                                               :+/`                                          -//`                                                                                              
        `osso`                      +yy         mMm`                                         -MMMo                                     +ys            yMMM.                                                   .NMMh                                                                                              -MMMy                                          sMM-                   /sh                                                                        
        +MMMM+                     `mMN         mMm`                                         `shy-                                    `NMm            :yho                                                    `ohy:                                                                                              `ohy-                                          sMM-                   dMM                                                                        
       `mMmNMm`     ++/    .++. .++oNMN+++++.   mMm-+sso/`      -+ssso:`     ++/`/oss+.    /+++++.      `+++++++++/    `:+osss+-   .++oNMN+++++`   .++++++         -+ssso:`    -++.:osso-                   /+++++-        `:ossso+.                  -++`-osso-      -+sss+-       -/oso++s-   :++`   `++:    /+++++-       :++`:oss+.     `/osso/`      `-+osodMM-               `+++mMM+++++-    `-+sss+:`                                                     
       oMM/oMMo     NMd    /MM/ -dddMMMddddd-   mMMNNddMMd`   .hMMmhdMMm:    mMNNMmhNMN-  `yddmMM:      `hdddddNMMy    /MNdhhNMMy  :dddMMNddddd.   :dddMMN       -dMMdhdMMm:   +MMNMmhNMM/                  sddmMMo       -mMNhyhdm:                  oMMdMNhmMMo   `yMMdydMMd.   -hMMdyhNMM/   yMM.   `MMy    yddmMM+       hMMmMmhNMN/   +mMmyhNMN+    :dMNdhdNMM-               `dddNMMddddd:   -dMMdhmMMm-                                                    
      .NMd `mMN.    NMd    /MM/    `mMN         mMMh.  oMM+  `mMN:   -mMN-   mMMd:  /MMy      +MM:           `sMMy`    `.    `hMM-    `NMm             mMN      .NMN-   -NMN.  +MMN/  .NMd                     :MMo       yMM/                        oMMNo` `mMm` `hMN:   :MMd  `mMm-   /MM/   yMM.   `MMy       /MM+       hMMm/  .NMd  /MMy`  `hMM-  -NMd.   sMM-                   dMM        .NMm-   :NMN`                                                   
      yMM:  +MMy    NMd    /MM/    `mMN         mMm`   :MM+  /MMo     +MMo   mMm`   `++:      +MM:          .dMN+       ./oooodMM:    `NMm             mMN      +MM+     oMM+  +MM/    dMm                     :MMo       :NMMho/.                    oMM/    :++` -MMm++++omMM` +MM+    /MM/   yMM.   `MMy       /MM+       hMN-    /+/  hMMs++++yMMo  sMM:    sMM-                   dMM        oMM/     oMM/                                                   
     :MMNooooNMN-   NMd    /MM/    `mMN         mMm`   :MM+  +MM+     :MMo   mMm`             +MM:         /NMm-       yMMmyssdMM:    `NMm             mMN      oMM/     /MM+  +MM/    dMm                     :MMo        `/ydNMMm/                  oMM:         :MMmhhhhhhhh  oMM:    /MM/   yMM.   `MMy       /MM+       hMN.         dMMhhhhhhhh/  yMN.    sMM-                   dMM        sMM:     +MM/                                                   
     dMMmddddmMMh   NMm`  `hMM/    `mMN`        mMm`   :MM+  -MMd`    hMM:   mMm`             +MM:       `sMMy`       :MMh    yMM:    `NMm             mMN      :MMh     dMM-  +MM/    dMm                     :MMo            `:NMN.                 oMM:         .NMm`         /MMs   -dMM/   yMM.   oMMy       /MM+       hMN.         yMM/          sMM/   :mMM-                   dMM`       /MMy    `dMM.                                                   
    /MMy     `dMM:  hMMy/omMMM/     sMMh+//o.   mMm`   :MM+   sMMd+:+dMMo    mMm`         .+++yMMs++/   `dMMm++++++`  -MMm//omMMM:     yMMh//+o.   /+++NMN+++-   yMMd+:+dMM+   +MM/    dMm                 `/++sMMh+++`   oo+/:/oNMd`                 oMM:          +MMmo/:/+o-  `dMMs/yNMMM/   +MMd/+dMMMy   .+++yMMy++/`   hMN.         .mMMy/::/o+   .NMNo/yMMMM-                   oMMd+//o-  `yMMh+:+mMN+                                                    
    ydd.      :ddy  `smNNmy/dd:     `+hmmmmd-   ydh`   -dd/    :ydmNmds-     hdy`         /dddddddddh`  -dddddddddd`   /hmNmmyodd-     `ohmmmmd.   yddddddddd+    /ymmNmds-    /dd:    ydy                 -dddddddddd.   sdmmNmmh+`                  +dd-           -sdmNNmmh:   .smNmdssMM/    +dmNmh/hdo   :dddddddddd`   sdd`          `+hmmNmmds    .ymNmdo+dd-                    +hmmmmd:    /ymmNmds.                                                     
                      ````             ````                      ````                                                    ````             ````                      ````                                                   ``````                                       `````       ```` /MM/      ```                                        `````        ```                            `````       ````                                                        
                                                                                                                                                                                                                                                                                         /MM/                                                                                                                                                                     
                                                                                                                                                                                                                                                                                         :hh:                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                ``                                                                                                                                                                                                    ``````            ..                      ```                                                                                               
                                                                                                    .::        :mm/                                                                                                                                                                                       `.::::-.   `hmmmmm:         `hmms                     hmh                                                                                               
                                                                                                   `mNd        /MM+                                                                                                                                                                                     `+dNNNmNNm:   -::sMM/         `hNNy                    `mMm                                                                                               
                                         ...     ..`      .----..       .---.`                  `..-NMm.....   /MM+`.--.`       `.---.                    `.. `.--.`       .---.`        .----..       `----`     `..`    ...    `.. `.--.        `.---.`      `.---.                                  `hMMy:...:o-      +MM/       `..-/:.          `.---.`   `mMm    `...                                                                                       
                                         hmm`   .mm+    -hmNmmmmh`    :hmNmNNd+`                :mmmMMMmmmmm.  /MMhdNmNNh-    `odNmmNmy:                  +mmodNNNNd-    :hmmmNNd+`    -hmNmmmmh`    -ymNmNNmy-   /mm/    hmd    ymmodNNNNh.    .odmNmmmm`   `+dNmmNmh:                                yMMo`             +MM/       smmmNmo        .odmNmmmm   `mMm  `+mmd/                                                                                       
                                         dMN`   -MMo   `mMm:..-::    +NMy:.-sMMs                `--:NMm-----`  /MMMd/-+MMd   `hMN+-./dMN-                 oMMMd/-/NMd`  +NMy-.-yMMo   `mMN:..-::    /NMd/--+mMN:  +MM/    dMm    hMMMh/-oMMy   -mMNs:--/o`  `hMN+-./dMN:                              `NMN`              +MM/       .--/MMs       -mMNs:--/o   `mMm :hMNy.                                                                                        
                                         dMN`   -MMo   `mMNo:.`     `NMN-....mMN`                  `NMd        /MMy`   dMN`  +MMs..../MMy                 oMMs`   ydh` .NMm-...-mMN   `mMNo:.`      mMN.    :MMh  +MM/    dMm    hMM+`  `hdh   hMM/         /MMs..../MMy                              .MMd               +MM/          -MMs       dMM:         `mMmsNMh:                                                                                          
                                         dMN`   -MMo    -ymNMNdy:   .MMNmmmmmNNN.                  `NMd        /MM+    hMN`  sMMmmmmmmNNy                 oMM:     ``  -MMNmmmmmNNN`   -ymNMNdy:   `MMd     `mMm  +MM/    dMm    hMN.    ```   NMm`         sMMmmmmmmNNy                              .MMm               +MM/          -MMs       MMm          `mMMMMm-                                                                                           
                                         dMN`   :MMo      `-/omMM+  .MMm--------                   `NMd        /MM+    hMN`  oMMo-------.                 oMM:         -MMd--------      `-:omMM+  `NMm`    -NMh  +MM/   `mMm    hMN.          mMN-         oMMs-------.      `--.                     dMM+              +MM/          -MMs       NMN.         `mMm/mMm+`                                                                                         
                                         yMM/`.oNMMo   `-.````+MMs   yMMs.````.`                    mMN:```.   /MM+    hMN`  -NMm/.```..                  oMM:         `hMMo.````.`   `-.````+MMy   sMMy.``:dMN:  :MMy.`:dMMm    hMN.          +MMd:.``.:   .NMN/.```..      `hNMm:                    :NMNs-.`.-+.  ````oMM+```    ```:MMy```    oMMd:.``.:   `mMm .yMMh-                                                                                        
                                         -mNNmNNdNMo   -NNmddmNNy.   `smNNdddmN+                    :mNNmdmN-  /MM+    hMm`   :dNNmdddmm.                 oMM:          `yNNNdddmN/   -NNmddmNNh.   `omNNdmNNh:   `yNMmmNmmMm    yMN.           /dNNmmmNN`   -dNNmdddmm.     `mMMN+                     -yNNNmmNNN:  /mmmNMMmmmd`  .dmmmMMNmmm-   `+mNNmmmNN   `dMd   +mMm+                                                                                       
                                          `:/+/- ::.   `:///+/:.       `://+/:-`                     `-////:`  `::.    -::      .:/+//:-                  .::`            `:/+//:-`   `-///+/:.       `:/+/:.       -/+/:`.:-    -::`             -:///:-      .:/+//:-       .//:                        `:////:.   .::::::::::   `::::::::::`     `-:///:.    -:-    .:::`                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                 /oo/ ooo.                                                                                                        :oo+ +oo-                                                                                                                        `oso`                                                                                                                                                          
                                                 sMMs`mMM-                                                                                           +dN`         +MMh dMM/                    -hm/                                                                                 +dN`           +MMM+                                                                                                                                                          
                                                 oMM+ dMM.                                                                                           hMM`         :MMy yMM:                    /MM+                                                                                 hMM`           `+o+`                                                                                                                                                          
                                                 /NN/ hNN       `/shhhys-     :shddho:    /ys-ohdhy/    .yy:+yddy+`     `+yddhs/`      -oyhhhy+  `yyyNMMyyyyy:    -NNo sNN.                 oyydMMdyyyyo     :shddho:                     -oyhhhy/     -oyddhs/`    oyo:shdhs-  `yyymMMyyyyy:   `syyyyy.      :ys:ohdhy/    .yy/    /ys`    -ohddho-                                                                                                              
                                                  ``   ``      /mMNhssym/   .dMMhosdMMy`  oMMMNysdMM+   :MMMMhshMMy    /NMmooyMMd`   `hMMmsosdh  `sssmMMyssss:     ``   ``                  +sshMMdsssso   .dMMhosdMMy`                 .hMMdsoydy    sNMdsohMMm-   dMMMmssNMN- `sssmMMyssss:   `sssmMM-      +MMMNhsdMMo   -MMy    sMN.   sNMhoodMNs                                                                                                             
                                                              -NMm-    `   `dMM:   `yMMo  oMMh.  .NMd   :MMm:   dMN`  -NMh`   /MMs   hMMo`    `      hMM`                                      /MM+        hMM:   `sMMo                `dMM+`    `   +MMs`   :MMd`  dMMs`  :MMo     hMM`            yMM-      +MMd-  `mMm   -MMy    sMN.  +MMo   `yMM:                                                                                                            
                                                              sMM/         .MMh     .NMh  oMM:   `mMd   :MMs    yMN`  oMMdyyyyhMMd  .MMd             hMM`                                      /MM+       .MMh     .NMd                -MMh          dMN.     hMM.  dMN`   .MMo     hMM`            yMM-      +MM/    dMm   -MMy    sMN.  dMMhyyyydMMo                                                                                                            
                                                              sMM:         .MMh     .NMh  oMM:   `mMd   :MMo    yMN`  oMMhooooooo+  .MMh             hMM`                                      /MM+       .MMh     .NMh                -MMy          dMN.     dMN.  dMN`   .MMo     hMM`            yMM-      +MM/    dMm   -MMy    sMN.  dMMsooooooo:                                                                                                            
                                                              /MMd.        `mMN:   `yMM/  oMM:   `mMd   :MMo    yMN`  :MMh`         `mMN/            hMM-                                      /MMs       `dMN:   `sMM+                `mMN:         oMMs`   /NMh   dMN`   .MMo     yMM-            yMM-      +MM/    dMm   .MMh   /NMN.  sMMo`            `shho`                                                                                                 
                                                               oNMNyooym/   :mMNyosdMNo   oMM:   `mMd   :MMo    yMN`   oNMms++osh.   -mMNdsosdh      /NMmsosy/                                 .mMNhooys   -mMNyosdMNs                  :mMNhsosdy   `hMMdoohNMh.   dMN`   .MMo     /NMmyosy/   :sssmMMyss+   +MM/    dMm   `hMMyohNNMN.  `hMMds+osys      :MMMM:                                                                                                 
                                                                -oyhhhys.    .+yhdhyo-    /yy-    syo   .yy/    +yy`    -oyhdhhys`    `/shhhhy+       -shhhhy:                                  .+yhhhho    ./yhdhyo-                    `/shhhhy/    `:shhhhs:`    oyy`   .yy/      -oyhhhy:   /yyyyyyyyyo   :yy-    oys    `ohhhy+/yy`   `:shhdhhy+      `shho`                                                                                                 
                                                                                 `                                          ``                                                                                  ``                                        ``                                                                    ``             ``            ``                                                                                                   
        </pre>